--Drop foreign key n?u c�
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE NHANVIEN'
            || ' DROP CONSTRAINT fk_NHANVIEN_QUANLI' || ' DROP CONSTRAINT fk_NHANVIEN_QUANLI';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2443 AND SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
--
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE NHANVIEN'
            || ' DROP CONSTRAINT fk_NHANVIEN_PHONGBAN' || ' DROP CONSTRAINT fk_NHANVIEN_PHONGBAN';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2443 AND SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
--
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PHONGBAN'
            || ' DROP CONSTRAINT fk_TRPHG_NHANVIEN' || ' DROP CONSTRAINT fk_TRPHG_NHANVIEN';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2443 AND SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
--
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE DEAN'
            || ' DROP CONSTRAINT fk_DEAN_PHONGBAN' || ' DROP CONSTRAINT fk_DEAN_PHONGBAN';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2443 AND SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
--
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PHANCONG'
            || ' DROP CONSTRAINT fk_PHANCONG_DEAN' || ' DROP CONSTRAINT fk_PHANCONG_DEAN';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2443 AND SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
--
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE PHANCONG'
            || ' DROP CONSTRAINT fk_PHANCONG_NHANVIEN' || ' DROP CONSTRAINT fk_PHANCONG_NHANVIEN';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2443 AND SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
--Drop table n?u c�
DROP TABLE NHANVIEN CASCADE CONSTRAINTS;
DROP TABLE PHONGBAN CASCADE CONSTRAINTS;
DROP TABLE DEAN CASCADE CONSTRAINTS;
DROP TABLE PHANCONG CASCADE CONSTRAINTS;
/
CREATE TABLE NHANVIEN (
  MANV varchar(10),
  TENNV VARCHAR2(100),
  PHAI VARCHAR2(5),
  NGAYSINH DATE,
  DIACHI VARCHAR2(200),
  SODT number(10),
  LUONG NUMBER(15,2),
  PHUCAP NUMBER(10,2),
  VAITRO VARCHAR2(50),
  MANQL varchar(10),
  PHG NUMBER(5),
  CONSTRAINT NHANVIEN_pk PRIMARY KEY (MANV)
  
);
/
CREATE TABLE PHONGBAN(
 TENPB VARCHAR2(50),
  MAPB NUMBER(5),
 TRPHG  varchar(10),
 CONSTRAINT PHONGBAN_pk PRIMARY KEY (MAPB)
 );
/
CREATE TABLE DEAN(
MADA NUMBER(5),
TENDA VARCHAR2(50),
PHONG NUMBER(5),
NGAYBD DATE,
CONSTRAINT DEAN_pk PRIMARY KEY (MADA)
);
/
CREATE TABLE PHANCONG (
MANV varchar2(10),
MADA NUMBER(5),
THOIGIAN number(5),
CONSTRAINT PHANCONG_pk PRIMARY KEY(MANV,MADA)
);
/
-----
ALTER TABLE NHANVIEN
ADD CONSTRAINT fk_NHANVIEN_QUANLI
FOREIGN KEY  (MANQL) 
REFERENCES NHANVIEN(MANV);
/
--- 
ALTER TABLE NHANVIEN
ADD CONSTRAINT fk_NHANVIEN_PHONGBAN
FOREIGN KEY (PHG)
REFERENCES PHONGBAN(MAPB);
/
----
ALTER TABLE PHONGBAN
ADD CONSTRAINT fk_TRPHG_NHANVIEN
FOREIGN KEY (TRPHG)
REFERENCES NHANVIEN(MANV);
/
----
ALTER TABLE DEAN
ADD CONSTRAINT fk_DEAN_PHONGBAN
FOREIGN KEY (PHONG)
REFERENCES PHONGBAN(MAPB)
/
---
ALTER TABLE PHANCONG
ADD CONSTRAINT fk_PHANCONG_DEAN
FOREIGN KEY (MADA)
REFERENCES DEAN(MADA);
/
---
ALTER TABLE PHANCONG
ADD CONSTRAINT fk_PHANCONG_NHANVIEN
FOREIGN KEY (MANV)
REFERENCES NHANVIEN(MANV);
/
----------------
--Insert d? li?u m?u
INSERT ALL
into PHONGBAN
values('T�i ch�nh', 1, null)
into PHONGBAN
values('K? ho?ch', 2, null)
into PHONGBAN
values('Nh�n s?', 3, null)
SELECT * FROM dual;
/
----
INSERT ALL
INTO NHANVIEN (MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT, LUONG, PHUCAP, VAITRO, MANQL, PHG)
VALUES ('TP01', 'Nguyen Van A', 'Nam', TO_DATE('01-01-1990', 'DD-MM-YYYY'), 'So 1, Nguyen Hue, Ha Noi', 1111111111, 10000.00, 3000.00, 'Tr??ng ph�ng', null, 1)
INTO NHANVIEN (MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT, LUONG, PHUCAP, VAITRO, MANQL, PHG)
VALUES ('TP02', 'Tran Thi B', 'Nu', TO_DATE('02-02-1995', 'DD-MM-YYYY'), 'So 2, Le Loi, Ho Chi Minh', 2222222222, 9000.00, 2500.00, 'Tr??ng ph�ng', null, 2)
INTO NHANVIEN (MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT, LUONG, PHUCAP, VAITRO, MANQL, PHG)
VALUES ('GD02', 'Le Van C', 'Nam', TO_DATE('03-03-1988', 'DD-MM-YYYY'), 'So 3, Nguyen Trai, Da Nang', 3333333333, 11000.00, 4000.00, 'Gi�m ??c', null, 2)
INTO NHANVIEN (MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT, LUONG, PHUCAP, VAITRO, MANQL, PHG)
VALUES ('QL01', 'Ho Thi D', 'Nu', TO_DATE('04-04-1993', 'DD-MM-YYYY'), 'So 4, Tran Hung Dao, Ha Noi', 4444444444, 12000.00, 4500.00, 'QL tr?c ti?p', null, 3)
INTO NHANVIEN (MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT, LUONG, PHUCAP, VAITRO, MANQL, PHG)
VALUES ('NS01', 'Nguyen Van E', 'Nam', TO_DATE('05-05-1998', 'DD-MM-YYYY'), 'So 5, Le Duan, Ho Chi Minh', 5555555555, 13000.00, 5000.00, 'Nh�n s?', null, 3)
INTO NHANVIEN (MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT, LUONG, PHUCAP, VAITRO, MANQL, PHG)
VALUES ('TC01', 'Tran Thi F', 'Nu', TO_DATE('06-06-1985', 'DD-MM-YYYY'), 'So 6, Nguyen Van Linh, Da Nang', 6666666666, 14000.00, 5500.00, 'T�i ch�nh', null, 1)
INTO NHANVIEN (MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT, LUONG, PHUCAP, VAITRO, MANQL, PHG)
VALUES ('TDA01', 'Le Van G', 'Nam', TO_DATE('07-07-1991', 'DD-MM-YYYY'), 'So 7, Tran Quoc Toan, Ha Noi', 7777777777, 15000.00, 6000.00, 'Tr??ng ?? �n', null,1 )
INTO NHANVIEN (MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT, LUONG, PHUCAP, VAITRO, MANQL, PHG)
VALUES ('NV01', 'Ho Thi H', 'Nu', TO_DATE('08-08-1996', 'DD-MM-YYYY'), 'So 8, Nguyen Van Cu, Ho Chi Minh', 8888888888, 16000.00, 6500.00, 'Nh�n vi�n','QL01', 3)
INTO NHANVIEN (MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT, LUONG, PHUCAP, VAITRO, MANQL, PHG)
VALUES ('NV02', 'Nguyen Van I', 'Nam', TO_DATE('09-09-1992', 'DD-MM-YYYY'), 'So 9, Tran Duy Hung, Ha Tinh', 9999999999, 17000.00, 7000.00, 'Nh�n vi�n', 'QL01', 3)
INTO NHANVIEN (MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT, LUONG, PHUCAP, VAITRO, MANQL, PHG)
VALUES ('NV03', 'Nguyen Van K', 'Nam', TO_DATE('09-07-1997', 'DD-MM-YYYY'), 'So 9, Tran Duy Hung, Da Nang', 1010101010, 18000.00, 8000.00, 'Nh�n vi�n',null, 2)
INTO NHANVIEN (MANV, TENNV, PHAI, NGAYSINH, DIACHI, SODT, LUONG, PHUCAP, VAITRO, MANQL, PHG)
VALUES ('NV04', 'Nguyen Van L', 'Nam', TO_DATE('09-07-199', 'DD-MM-YYYY'), 'So 9, Tran Duy Hung, Da Nang', 1010101011, 19000.00, 8000.00, 'Nh�n vi�n',null,1 )
SELECT * FROM dual;
/

------

----
INSERT ALL
INTO DEAN (MADA, TENDA, PHONG, NGAYBD) VALUES (1, 'Khoa A', 1, TO_DATE('01-01-2022', 'DD-MM-YYYY'))
INTO DEAN (MADA, TENDA, PHONG, NGAYBD) VALUES (2, 'Khoa B', 2, TO_DATE('02-02-2022', 'DD-MM-YYYY'))
INTO DEAN (MADA, TENDA, PHONG, NGAYBD) VALUES (3, 'Khoa C', 3, TO_DATE('03-03-2022', 'DD-MM-YYYY'))
INTO DEAN (MADA, TENDA, PHONG, NGAYBD) VALUES (4, 'Khoa D', 1, TO_DATE('04-04-2022', 'DD-MM-YYYY'))
INTO DEAN (MADA, TENDA, PHONG, NGAYBD) VALUES (5, 'Khoa E', 3, TO_DATE('05-05-2022', 'DD-MM-YYYY'))
SELECT * FROM dual;
/
---
INSERT ALL

INTO PHANCONG (MANV, MADA, THOIGIAN) VALUES ('TDA01', 1, 24)
INTO PHANCONG (MANV, MADA, THOIGIAN) VALUES ('TC01', 1, 24)

INTO PHANCONG (MANV, MADA, THOIGIAN) VALUES ('NV03', 2, 8)

INTO PHANCONG (MANV, MADA, THOIGIAN) VALUES ('NV01', 3, 8)
INTO PHANCONG (MANV, MADA, THOIGIAN) VALUES ('QL01', 3, 10)

INTO PHANCONG (MANV, MADA, THOIGIAN) VALUES ('NV04', 4,10)
INTO PHANCONG (MANV, MADA, THOIGIAN) VALUES ('TC01', 4, 8)

INTO PHANCONG (MANV, MADA, THOIGIAN) VALUES ('NV02', 5, 16)
INTO PHANCONG (MANV, MADA, THOIGIAN) VALUES ('QL01', 5, 8)
SELECT * FROM dual;
/
----
SELECT * FROM NHANVIEN;
/
SELECT * FROM DEAN;
/
SELECT *  FROM PHANCONG;
/
SELECT * FROM PHONGBAN;
/

UPDATE QLNV.PHONGBAN SET TRPHG = 'TP01' WHERE MAPB = 'PB01';
UPDATE QLNV.PHONGBAN SET TRPHG = 'TP01' WHERE MAPB = 'PB02';