create role R_QLTT;
/
CREATE USER QL01 IDENTIFIED BY QL01;--- QU?N LÍ TR?C TI?P
/
GRANT R_QLTT TO QL01;
/
grant create session to QL01;
/
GRANT SELECT ON QLNV.PHONGBAN TO R_QLTT;
GRANT SELECT ON QLNV.NHANVIEN TO R_QLTT;
GRANT SELECT ON QLNV.PHANCONG TO R_QLTT;
GRANT UPDATE ON QLNV.NHANVIEN TO R_QLTT;
GRANT SELECT ON QLNV.DEAN TO R_QLTT;
grant select on QLNV.view_decrypt_NHANVIEN_LUONG_PHUCAP to R_QLTT;