CREATE ROLE R_NHANVIEN;
alter session set "_ORACLE_SCRIPT"=true;
CREATE user NV01 IDENTIFIED BY NV01;
GRANT SELECT ON QLNV.NHANVIEN to R_NHANVIEN;
GRANT SELECT ON QLNV.PHANCONG TO R_PHANCONG;
grant SELECT on QLNV.PHONGBAN to R_NHANVIEN;
grant SELECT on QLNV.DEAN TO R_NHANVIEN;
GRANT UPDATE ON QLNV.NHANVIEN TO R_NHANVIEN;

GRANT R_NHANVIEN TO NV01;

